Add javadocs and a little cleanup
dappcoder/hello-swirld pull request #1
Opened 2018-04-17 12:08 UTC by ConnorChristie

I added the javadocs to the inherited methods from Swirlds as well as fixed the SDK download link in the README and added a gitignore for intellij and eclipse!

2018-04-17 13:38 UTC, dappcoder requested changes
Hi Connor!
Thanks so much for your contribution. I appreciate the cleanup. Please see a couple of comments on your changes.
I think this can evolve into some kind of a maven archetype or another template that would automatically allow developers to create apps from scratch.
Nice to meet you! 
Alex.

2018-04-17 13:38 UTC, dappcoder commented on pom.xml
> +        <swirlds.sdk>/users/connor/Documents/hashgraph/sdk</swirlds.sdk>
SDK location probably leaked from your local setup. I propose some generic unix path (or revert to "/home/swirlds/sdk") if nothing else comes to mind.

2018-04-17 13:38 UTC, dappcoder commented on README.md
> +Follow the pre-requisites, download and unzip the SDK to preferred location. See https://www.swirlds.com/download/
I think the previous url (https://dev.hashgraph.com/docs/installation/) is a better fit as it describes the prerequisites for installing the Hashgraph SDK (e.g. JCE) which are not reiterated here. That page also includes the download location for the sdk itself.

2018-04-18 03:12 UTC, ConnorChristie commented
I was also thinking about how convenient it would be if this was converted into an archetype! Nonetheless, thanks for the starter template.

2018-04-18 09:52 UTC, dappcoder requested changes
<mainClass>Main</mainClass> freezes Swirlds Browser. It expects a prefix before "Main" otherwise, it won't run. 
I suggest reverting the mainClass prop to HelloSwirldMain, the Main java class name to HelloSwirldMain and the State java class to HelloSwirldState.

2018-04-18 09:52 UTC, dappcoder commented on pom.xml
> +                            <mainClass>Main</mainClass>
I've built and run the module with HelloSwirldMain renamed to Main (and java classes renamed accordingly). It seems to be stuck and the console windows do not open. The SDK uses that prefix as an identifier for the app, so can't do without it.

2018-04-19 00:17 UTC, Coffee-Boyy commented
Good catch! I also added a note to the readme so nobody else runs into the same issue.

2018-04-23 13:25 UTC, dappcoder approved these changes

2018-04-23 13:28 UTC, merged